# Generated by Django 3.1 on 2020-08-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
